language: python

cache: pip
env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=pep8
    - TOXENV=coverage
before_install:
    - pip install --upgrade pip setuptools
install:
    - pip install tox
script:
    - tox -e $TOXENV
